pass in fragment
HedvigInsurance/giraffe pull request #1152
Opened 2021-04-27 08:44 UTC by tarikstafford

2021-04-27 08:48 UTC, sampettersson requested changes

2021-04-27 08:48 UTC, sampettersson commented on src/resolvers/cross-schema/quoteDetailsTable.ts
> +        fragment: fragment,
```suggestion
        fragment,
```

2021-04-27 08:48 UTC, sampettersson commented on src/resolvers/cross-schema/index.ts
> +      ...quoteDisplayName(getQuoteDetailsFragment("BundledQuote"))
```suggestion
      ...quoteDisplayName("BundledQuote")
```

2021-04-27 08:48 UTC, sampettersson commented on src/resolvers/cross-schema/index.ts
> +      ...quoteDisplayName(getQuoteDetailsFragment("CompleteQuote"))
```suggestion
      ...quoteDisplayName("CompleteQuote")
```

2021-04-27 08:48 UTC, sampettersson commented on src/resolvers/cross-schema/index.ts
> +function getQuoteDetailsFragment(quoteType:String): String {
```suggestion
const getQuoteDetailsFragment = (quoteType: String) => {
```

2021-04-27 09:13 UTC, hugokallstrom commented on src/resolvers/cross-schema/index.ts
>        },
Do we want these fragment definitions in `quoteDetailsTable` maybe? As `const`, `enum` or something else?

2021-04-27 10:48 UTC, sampettersson commented on src/resolvers/cross-schema/quoteDetailsTable.ts
> +      detailsTable(locale: Locale!): Table!
should we maybe have a `currentAgreementDetailsTable` and a `upcomingAgreementDetailsTable`? where current looks at current agreement and upcoming looks at upcomingAgreement, then its also easy to diff client-side to only show the changes.

2021-04-27 11:06 UTC, hugokallstrom commented on src/resolvers/cross-schema/quoteDetailsTable.ts
> +      detailsTable(locale: Locale!): Table!
Ok so rename `Contract` extension to `currentAgreementDetailsTable`, and `CompleteQuote` + `BundledQuote` to `upcomingAgreementDetailsTable`. Should we have those two as separate `crossSchemaExtensions` and re-use the resolve function?

2021-04-28 07:12 UTC, sampettersson commented on src/resolvers/cross-schema/quoteDetailsTable.ts
> +      detailsTable(locale: Locale!): Table!
@hugokallstrom no, not really, quotes are fine!

On contracts we have both the `Contract.currentAgreement` that we use on the contract subview to show the details + this new `ContractStatus.upcomingAgreement` that is used after the user has accepted the new quotes right?

2021-04-28 08:00 UTC, hugokallstrom commented on src/resolvers/cross-schema/quoteDetailsTable.ts
> +      detailsTable(locale: Locale!): Table!
Ah yes thats right, I'll add that!

2021-05-05 08:58 UTC, sampettersson approved these changes

2021-05-05 11:22 UTC, hugokallstrom commented on src/resolvers/cross-schema/detailstable/tableRenderer.ts
> +        this.textKeyMap = require(`${__dirname}/../../../translations/${locale}.json`)
Yes, it seems to work :)

2021-05-06 07:41 UTC, merged