Feature/create claim mutation
HedvigInsurance/giraffe pull request #1294
Opened 2021-07-22 15:20 UTC by anthansson

# Jira Issue: [MX-222]

## What?
- New mutation createClaim added. Adds ability to create a claim via a GraphQL mutation that communicates directly with claims-service. Previously when creating a claim the chain of communication was:  giraffe -> bot-service - claims service, since claims are created via the chat. Adding this mutation allows us to create a new workflow where members can create claims outside without using the chat. 

Tried to add snapshot test for creating claim and uploading file but didn't get it working. Added ticket to finish it later. 

## Optional checklist
- [ ] Unit tests written
- [ ] Tested locally
- [x] Codescouted

[MX-222]: https://hedvig.atlassian.net/browse/MX-222

2021-07-23 12:32 UTC, hedvigoscar commented
Seems like `src/generated/graphql.ts` may have been deleted by mistake 😬

2021-07-23 13:12 UTC, anthansson commented
Got merge conflicts everywhere so I simply deleted all its content 🤪  Will generate a new one

2021-07-30 08:12 UTC, hedvigoscar requested changes
Some things to look at wrt schema, and a few general improvements. Mostly good though!

2021-07-30 08:12 UTC, hedvigoscar commented on src/schema.graphqls
> +  createClaim(audioFile: Upload!): String!
Canonical GraphQL-schema design would suggest that this mutation should have the following signature:

```suggestion
  createClaim(audioFile: Upload!): Claim!
```

2021-07-30 08:12 UTC, hedvigoscar commented on src/schema.graphqls
> +  createClaim(audioFile: Upload!): String!
Then, from the `createClaim` mutation-resolver, you can call the same code path that is used for resolving a single claim, to promote maximum code reuse 🙂

2021-07-30 08:12 UTC, hedvigoscar commented on src/test-utils/test-server.ts
> -import { Upstream } from './../api/upstream';
Is this file formatted with `prettier`? It looks like it may have been de-formatted 🤔

2021-07-30 08:12 UTC, hedvigoscar commented on src/resolvers/createClaim.ts
> +      s3.upload(params, UPLOAD_OPTIONS, (err, data) => {
It would be neat to `promisify` this function, so that we can use appropriate `async`/`await`-syntax to call it, instead of callbacks.

It would probably look something like this:

```typescript
const s3Upload = (params, options) = new Promise((resolve, reject) => {
  s3.upload(params, options, (err, data) => {
    if (err) {
      reject(err)
      return
    }
    resolve(data)
  })
}
```

and we can then call it as such:

```typescript
const uploadedAudioURL = await s3Upload(...)
```

instead of having to create a weird chain of raw `Promise`-objects in our resolver function body 😄

2021-07-30 08:41 UTC, anthansson commented on src/api/upstreams/claimService.ts
> +      const res = await client.post(`/claims/createClaim`, createClaimDTO)
Got another pr regarding this issue :-) will deploy that one before this branch

2021-08-09 08:13 UTC, anthansson commented on src/test-utils/test-server.ts
> -import { Upstream } from './../api/upstream';
true was KtLint!

2021-08-10 12:29 UTC, anthansson commented on src/schema.graphqls
> +  createClaim(audioFile: Upload!): String!
For anyone reading this. After a claim is created axon triggers a few events that will be handled asynchronously, thus a claim object cannot be returned right away. I will simply return the claimId for now but perhaps we gotta take a look at how to handle such inconsistencies. Feels like either the front end or back must go through some major changes? 

https://stackoverflow.com/questions/64045477/how-to-make-command-to-wait-until-all-events-triggered-against-it-are-completed/64117171#64117171

2021-08-11 06:33 UTC, anthansson commented on src/api/upstreams/productPricing.ts
> +import { HttpClient } from '../httpClient'
just some formatting on this file

2021-08-11 09:48 UTC, anthansson commented on src/resolvers/chatResponse.ts
> +  const uploadedFileUrl = await s3Upload(params, UPLOAD_OPTIONS)
should I do any try-catch or just let giraffe throw errors? Will result in 500

2021-08-11 09:49 UTC, anthansson commented on src/resolvers/file.ts
> +      signedUrl: await s3GetSignedUrl(AWS_S3_BUCKET, key),
same questions in all uses of s3 functions. Should I try catch?

2021-08-11 09:49 UTC, anthansson commented on src/resolvers/uploadFile.ts
> +  await s3Upload(params, UPLOAD_OPTIONS)
same questions in all uses of s3 functions. Should I try catch?

2021-08-12 09:44 UTC, hedvigoscar commented on src/resolvers/chatResponse.ts
> +  const uploadedFileUrl = await s3Upload(params, UPLOAD_OPTIONS)
Any thrown errors should result in something like this:

```json
{
	"data": null",
	errors: [
		{
			// ...
		}
	]
}
```

The primary concern would be if the error message leaks any information. Behaviourally I would argue that this is correct.

2021-08-12 09:54 UTC, hedvigoscar approved these changes
Approved, with the caveat about Eventual Consistency remaining 🙂

2021-08-12 12:19 UTC, merged