Add some changes to claims query API
HedvigInsurance/giraffe pull request #1303
Opened 2021-07-29 15:33 UTC by anthansson

# Jira Issue: [MX-182, MX-224]

## What?
- Remove private field from claims in schema
- Add url signing functionality to claim files
- Also look for trials when fetching the contract to include in a claim

## Optional checklist
- [x] Unit tests written
- [x] Tested locally
- [x] Codescouted

2021-07-30 07:48 UTC, hedvigoscar requested changes
Looks mostly sensible! A few issues to address, nothing crazy though 😄

2021-07-30 07:48 UTC, hedvigoscar commented on src/resolvers/claims.ts
> +  if (!parentAsPrivate._contractId) return undefined
```suggestion
  if (!parentAsPrivate._contractId) {
    return undefined
  }
```

`if`-statements without curly braces are error-prone: https://embeddedgurus.com/barr-code/2014/03/apples-gotofail-ssl-security-bug-was-easily-preventable/

The following form works if we want to keep it as a one-liner, but really we should just go with whatever formatting `prettier` considers to be correct 🙂 

```suggestion
  if (!parentAsPrivate._contractId) { return undefined }
```

2021-07-30 07:48 UTC, hedvigoscar commented on src/resolvers/claims.ts
> +  if (!memberId) return undefined
```suggestion
  if (!memberId) {
    return undefined
  }
```

2021-07-30 07:48 UTC, hedvigoscar commented on src/resolvers/claims.ts
> +  if (contract) return transformContract(contract, context.strings)
```suggestion
  if (contract) {
    return transformContract(contract, context.strings)
  }
```

2021-07-30 07:48 UTC, hedvigoscar commented on src/resolvers/claims.ts
> +  if (fakeContract) return transformTrialToFakeContract(fakeContract, context.strings)
```suggestion
  if (fakeContract) {
    return transformTrialToFakeContract(fakeContract, context.strings)
  }
```

2021-07-30 07:48 UTC, hedvigoscar commented on src/resolvers/claims.ts
> +  // console.log("SIGN KEY:", key)
```suggestion
```

2021-07-30 07:48 UTC, hedvigoscar commented on src/resolvers/claims.ts
> +})
Might be wise to use `getSignedUrlPromise` (https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#getSignedUrlPromise-property)

```suggestion
const signURL = (bucket: String, key: String) => s3.getSignedUrlPromise('getObject', {
  Bucket: bucket,
  Key: key,
  Expires: THIRTY_MINUTES,
})
```

This change would change the signature of this from `string` to `Promise<string>`, which means that callers would need to `await` the call to `signURL`.

2021-08-01 09:08 UTC, anthansson commented on src/resolvers/claims.ts
> +})
getSignedUrlPromise does not seem exist in the version of the aws-sdk we are using. So I'll skip that for now? getSignedUrl is being used in more places as well.

2021-08-02 07:14 UTC, hedvigoscar commented on src/resolvers/claims.ts
> +})
I see! We can trivially create our own by wrapping it:

```typescript
const getSignedUrl = new Promise((resolve, reject) => {
  s3.getSignedUrl(
    'getObject',
	{
	  Bucket: bucket,
      Key: key,
  	  Expires: THIRTY_MINUTES,
  	},
    (err, url) => {
      if (err) {
		reject(err)
        return
	  }
      resolve(url)
    }
  )
})
```

2021-08-10 12:54 UTC, hedvigoscar approved these changes

2021-08-11 05:43 UTC, merged