Return current co-insured when cross-selling
HedvigInsurance/giraffe pull request #1369
Opened 2021-09-29 14:48 UTC by cpiehl1

# Jira Issue: []

## What?
- Return current number of co-insured on the base contract when cross-selling

## Why?
- So that this value can be default in the embark flow

## Optional checklist
- [ ] Unit tests written
- [ ] Tested locally
- [ ] Codescouted

2021-09-29 14:51 UTC, cpiehl1 commented on src/resolvers/crossSell.ts
> +          currentCoInsured ? `?coInsured=${currentCoInsured}` : ''
Is `coInsured` the correct key? Not sure how this is read inside the embark flow. @hugokallstrom

2021-09-30 09:16 UTC, hugokallstrom requested changes

2021-09-30 09:16 UTC, hugokallstrom commented on src/resolvers/crossSell.ts
> +          currentCoInsured ? `?coInsured=${currentCoInsured}` : ''
Looking at embark and the angel story, we already have a key called `householdSize`. This represents the input from the user. It would be really smooth if we could map this value to that key - so instead of passing `coInsured` here we pass `householdSize`. Does that make sense? Sorry for the hassle!

2021-09-30 09:26 UTC, cpiehl1 commented on src/resolvers/crossSell.ts
> +          currentCoInsured ? `?coInsured=${currentCoInsured}` : ''
Yes, this should be fine. How is it going to work for DK and NO thought? When creating quotes, `householdSize` is used in SE and `coInsured` in DK and NO. Is the embark flow `householdSize` regardless of market?

2021-09-30 09:27 UTC, hedvigoscar commented on src/resolvers/crossSell.ts
> +          currentCoInsured ? `?coInsured=${currentCoInsured}` : ''
We're using `householdSize` in the embark story as it makes more sense for the user. Later on, when submitting the API call, we calculate `numberCoinsured` instead by `householdSize - 1`

2021-09-30 09:31 UTC, cpiehl1 commented on src/resolvers/crossSell.ts
> +          currentCoInsured ? `?coInsured=${currentCoInsured}` : ''
Alright, sounds good! 😄

2021-10-01 13:17 UTC, vonElfvin approved these changes
Izi

2021-10-01 13:20 UTC, hugokallstrom approved these changes

2021-10-01 13:20 UTC, merged