add Swedish car
HedvigInsurance/giraffe pull request #1564
Opened 2022-04-19 16:16 UTC by AlexSJ1990

# Jira Issue: [IPC-557]

## What?
- Add Swedish Car to giraffe

## Why?
- to unblock clients

## Optional checklist
- [ ] Unit tests written
- [ ] Tested locally
- [ ] Codescouted

2022-04-20 07:15 UTC, sampettersson requested changes

2022-04-20 07:15 UTC, sampettersson commented on src/resolvers/quote-bundle/quoteBundle.graphqls
> +  | SwedishCarAgreement
This should be `SwedishCarDetails` right?

2022-04-20 07:15 UTC, sampettersson commented on src/cross-schema/contractPills.ts
> +                address {
We probably don't want the address here, its more a system thing that the insurance has an address rather than a conscious user decision, so we tend to remove it on insurances where it doesn't make too much sense.

2022-04-20 07:15 UTC, sampettersson commented on src/cross-schema/detailstable/contractDetailsFragments.ts
> +    address {
Same with the address here.

2022-04-21 07:06 UTC, sampettersson approved these changes
🎉

2022-04-21 08:18 UTC, cpiehl1 commented on src/resolvers/contracts/contracts.ts
> +import {format} from 'date-fns'
Looks like your formatting is a bit different, do you have prettier installed?

2022-04-21 08:21 UTC, cpiehl1 approved these changes
Looks great!

2022-04-21 08:28 UTC, AlexSJ1990 commented on src/resolvers/contracts/contracts.ts
> +import {format} from 'date-fns'
good point - have run prettier now :)

2022-04-21 08:31 UTC, merged